name: 恢复vless服务并发送Telegram消息

on:
  schedule:
    - cron: '*/30 * * * *'  # 每30分钟执行一次
  workflow_dispatch:

jobs:
  restore_and_notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: 设置Python环境
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # 替换为您需要的 Python 版本

      - name: Create accounts.json from environment variable
        run: echo "$ACCOUNTS_JSON" > accounts.json
        env:
            ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}  # 从GitHub Secrets中获取环境变量

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests  # 只需安装需要的依赖，此处假设使用 requests 发送 HTTP 请求
          pip install paramiko

      - name: 执行Python脚本恢复vless服务并发送Telegram消息
        env:
          ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}
          FEISHU_WEBHOOK_URL: ${{secrets.FEISHU_WEBHOOK_URL}}
        run: |
          python3 vless/check_and_start_vless.py
          python3 vless/check_and_start_vmess.py


